# -*- coding: utf-8 -*-
"""Statistics Day 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mm5Ip-n_4fBezAQuD80PHqZJncuq2u0d
"""

import pandas as pd

from google.colab import files
up=files.upload()

from google.colab import files
up=files.upload()

df1=pd.read_csv('i1.csv')
df2=pd.read_csv('i2.csv')

print("First dataset shape : ",df1.shape)
print("Second dataset shape : ",df2.shape)

df1.info()

df1.shape

df=df1.merge(df2,how='outer')

df.shape

df.head()

df.tail(10)

df=df.drop(['Sub Total','Discount','Table No.','Server Name','Covers',	'Variation','HSN'],axis=1)

df.head()

df.shape

df['Invoice No.'].unique()

df[df['Invoice No.']==23465]['Qty.']

print(df[df['Invoice No.']==23465]['Qty.'].sum())

x[x['Final Total']>2100]['Invoice No.']

y=df['Final Total'].sum()
print("Total revenue ",y)

#No of customers purchased
x=df['Invoice No.'].nunique()

#Average value
print("Average : ",y/x)

df.groupby("Item Name")["Qty."].sum()

df.groupby("Item Name")["Qty."].sum().sort_values(ascending=False)

# Top 5 Items based on the Quantity
x=df.groupby("Item Name")["Qty."].sum().sort_values(ascending=False)[0:5]
x

import seaborn as sns
sns.barplot(x)

x.plot(kind='bar')

# Total revenue on 15th may 2023
g=df[df["Date"]=="2023-09-15"]["Final Total"].sum()
print(g)

#Alternative way
df.groupby("Date")["Final Total"].sum()["2023-09-15"]

# Find the quantity of Chicken noodles on various days
print("2023-04-23 : ",df[(df["Item Name"]=="Chicken Noodles")&(df["Date"]=="2023-04-23")]["Qty."].sum())
print("2023-09-15 : ",df[(df["Item Name"]=="Chicken Noodles")&(df["Date"]=="2023-09-15")]["Qty."].sum())
print("2023-07-13 : ",df[(df["Item Name"]=="Chicken Noodles")&(df["Date"]=="2023-07-13")]["Qty."].sum())

g=df.groupby("Invoice No.")["Final Total"].sum()
g[g>2100]

# the invoice when the final total is 2887.50
df[df["Final Total"]==2887.50]["Invoice No."]

#the ITem name, Quantity and final total when invoice no is 28145
df[df["Invoice No."]==28145][["Item Name","Qty.","Final Total"]]

# WordCloud
from wordcloud import WordCloud

text=" ".join(df['Item Name'].dropna().astype(str).values)
word=WordCloud(background_color='Green',height=678,width=853).generate(text)
fig,ax=plt.subplots(figsize=(20,14))
ax.set_title("Items name")
ax.imshow(word,interpolation='bilinear')
plt.show()

text=" ".join(df['Item Name'].dropna().astype(str).values)
word=WordCloud(background_color='Green',height=678,width=853).generate(text)
fig,ax=plt.subplots(figsize=(20,14))
ax.set_title("Items name")
ax.set_xticks([])
ax.set_yticks([])
ax.imshow(word,interpolation='bilinear')
plt.show()

text=" ".join(df['Item Name'].dropna().astype(str).values)
word=WordCloud(background_color='Green',height=678,width=853).generate(text)
fig,ax=plt.subplots(figsize=(20,14))
ax.set_title("Items name")
ax.set_xticks([])
ax.set_yticks([])
ax.imshow(word,interpolation='bicubic')
plt.show()

text=" ".join(df['Item Name'].dropna().astype(str).values)
word=WordCloud(background_color='Green',height=678,width=853).generate(text)
fig,ax=plt.subplots(figsize=(20,14))
ax.set_title("Items name")
ax.set_xticks([])
ax.set_yticks([])
ax.imshow(word,interpolation='nearest')
plt.show()

text=" ".join(df['Item Name'].dropna().astype(str).values)
word=WordCloud(background_color='Green',height=678,width=853).generate(text)
fig,ax=plt.subplots(figsize=(20,14))
ax.set_title("Items name")
ax.set_xticks([])
ax.set_yticks([])
ax.imshow(word,interpolation='gaussian')
plt.show()

text=" ".join(df['Item Name'].dropna().astype(str).values)
word=WordCloud(background_color='Green',height=678,width=853).generate(text)
fig,ax=plt.subplots(figsize=(20,14))
ax.set_title("Items name")
ax.set_xticks([])
ax.set_yticks([])
ax.imshow(word,interpolation='quadric')
plt.show()

text=" ".join(df['Item Name'].dropna().astype(str).values)
word=WordCloud(background_color='Green',height=678,width=853).generate(text)
fig,ax=plt.subplots(figsize=(20,14))
ax.set_title("Items name")
ax.set_xticks([])
ax.set_yticks([])
ax.imshow(word,interpolation='hamming')
plt.show()